### ISSUE TITLE
How to name a health card?

### ISSUE THREAD

**Issue by vsmahesh** [smart-on-fhir/health-cards#134]
What if I want to name a health card? Is it fine to include the name as a claim `sub: "Covid-19 Vaccination Record"` or do you have any other thoughts?

**Comment by jmandel** [comment]
In general we aim to keep Health Cards focused on structured computable data rather than human facing labels; in your example, any system can already tell that this is 1) a Health Card, 2) a Covid 19 Health Card, 3) an Immunization Health Card, simply ny inspecting the array of computable types (`.vc.type[]`), following https://smarthealth.cards/vocabulary/.

Can you say more about what else a "name" would convey? It gets complicated when we think about who would assign a name, what would be its intended use, and who would be the intended users? Who would be responsible for translation into different languages? How would we ensure that names are accurate and concise?

**Comment by vsmahesh** [comment]
I just wanted to put a title for the card in the UI. I am imagining about a health wallet application that can be used to collect and later present the health cards.

Are you saying that we should infer the title based on the available `.vc.types[]`. If it contains `https://smarthealth.cards#covid19` and `https://smarthealth.cards#laboratory` infer it as a "Covid-19 Lab Test"?

**Comment by jmandel** [comment]
Yes, the expectation is for client applications to read the structured data to understand what the card contains. Since different apps will have different needs, it's not clear how we'd express requirements for a one-size-fits-all title that communicates anything beyond the set of types. Re: multiple immunizations, we do document in the spec that unrelated immunizations should be documented in separate Health Cards, so that they can be managed and presented separately.

I'm going to close this for now -- appreciate the feedback, and please do follow up to let us know if you encounter issues generating titles from types.
