### ISSUE TITLE
Space savings: Drop numeric mode and just use base64

### ISSUE THREAD

**Issue by jtmcdole** [smart-on-fhir/health-cards#158]
Using "numeric mode" as described inflates the data ~200% in size compared to the exact same data in JWT form.

| CA COVDI QR | size |
| --- | --- |
| Numeric Mode | 1703|
| base64 JWT | 854|

Benefits:
1. Smaller QR codes
2. More data before splitting required
3. Less steps to decode JWS

You can continue to split larger tokens across multiple QR codes using the `shc:/N/C/` method described.

**Comment by jmandel** [comment]
This assessment is looking at character counts in the QR contents, but you need to also take encoding density into account: a V22 QR can fit 2409 numeric mode characters, or 1003 byte mode characters (see https://www.qrcode.com/en/about/version.html)

(Keep in mind that we avoid binary mode QR segments because we want the full value to be displayable and copy/paste-able.)

Is this clear? Happy to provide a more detailed explanation if it helps. (There are approaches that could make these QRs slightly denser, but at a cost of some complexity; I don't think we've missed low hanging fruit.)

**Comment by laurencebgood** [comment]
I'm having trouble reconciling the logic you present, @jmandel, which matches the spec, with the actual QR codes generated. They aren't very dense at all and just using command line "qrencode" I can produce denser, "better" (easier to scan) codes in byte mode. I'm guessing the difference is the encoder being used. I need to play around a bit with libqrencode, since the command line tool doesn't support numeric mode. It's possible that library would produce a "better" numeric QR code than the library you are using. I also should admit that I didn't play with a large sample set, just my own SHC.

**Comment by jmandel** [comment]
See https://github.com/smart-on-fhir/health-cards/wiki/Libraries-for-SMART-Health-Cards#what-are-good-libraries-for-qr-generation for details; sounds like you're generating a segment in bytes mode that's full of numbers, which would indeed be inefficient.  You might want to run the validator at https://github.com/microsoft/health-cards-validation-SDK for one way to see what's going on.

**Comment by jtmcdole** [comment]
Thanks for the response @jmandel  - and you're right, I didn't consider that QR codes had another encoding method for a limited character set. A quick look at the raw byte stream from ZXing shows the sizes are:  782 (numeric) vs 861 (ascii+base64).

I agree; being able to copy a string if valuable.  Unpacked that string is much larger (which is where I was taking my measurements from).

Again, thank you for your response!

**Comment by jtmcdole** [comment]
Side note for anyone else not an expert; I found this link to be very informative as well: https://www.nayuki.io/page/creating-a-qr-code-step-by-step

**Comment by nayuki** [comment]
> This assessment is looking at character counts in the QR contents, but you need to also take encoding density into account

Indeed. Try this tool: https://www.nayuki.io/page/optimal-text-segmentation-for-qr-codes . Especially look at the "SGQR payment" example!

**Comment by jtmcdole** [comment]
@nayuki - as a matter of fact, that is super helpful because the "shc:/[0-9]*" gets encoded exactly as described here.
