### ISSUE TITLE
Specify FHIR API response when no SMART Health Cards are available

### ISSUE THREAD

**Issue by p2-apple** [smart-on-fhir/health-cards#163]
Today [we specify](https://spec.smarthealth.cards/#via-fhir-health-cards-issue-operation) that the response to the `$health-cards-issue` operation:

> The response is a `Parameters` resource that includes **one more more** verifiableCredential values [...]

This omits what servers should do when a patient does not have Health Cards available. We should add language about the expected outcome of the operation when zero cards are available.

**Comment by jmandel** [comment]
I'd lead toward the `200` with a Parameters resource (and no actual named params inside because ... there are zero). I like this by analogy to a FHIR Search, which returns a Bundle with 0 entries when the search matches no resources.

(And in the future if we want to attach additional response properties like "timeUntilNextHealthCardIsAvailable" or whatever, we don't need to rework the response status codes / semantics.)

**Comment by jmandel** [comment]
@p2-apple if this makes sense to you, would you submit a PR?

**Comment by lcmaas** [comment]
Note that the output parameter verifiableCredential is 1..* in the OperationDefinition so that would also need to be changed to 0..*
