### ISSUE TITLE
Create new github release matching spec's changelog version

### ISSUE THREAD

**Issue by christianpaquin** [smart-on-fhir/health-cards#209]
It's not entirely clear that the framework version is listed in the [change log](https://spec.smarthealth.cards/changelog/); this can lead to confusion when discussing spec updates (see [this discussion](https://github.com/smart-on-fhir/health-cards/discussions/207#discussioncomment-1688012)). I'd suggest:
1. Explicitly putting the version number in the [status](https://spec.smarthealth.cards/#status) section of the spec, something like:
 "The current version of the framework is 1.1.1; see the revision history in the [change log](changelog)."
2. Either remove or keep the github releases up-to-date (the last one is still [v1.0.0-rc](https://github.com/smart-on-fhir/health-cards/releases)).

**Comment by christianpaquin** [comment]
Just saw #208, pointing out the same issue.

**Comment by jmandel** [comment]
Thanks! I like the idea of number one, and for number two we might just want to clear out any releases because we are not actively making use of this feature and have not done so historically.

Do you want to cover (1) with a PR,? (And if there's any convenient build time way to grab that value from a file,  that might help  prevent us from forgetting to update in both places in the future.)

**Comment by christianpaquin** [comment]
> for number two we might just want to clear out any releases because we are not actively making use of this feature and have not done so historically.

Agreed.

> Do you want to cover (1) with a PR,? (And if there's any convenient build time way to grab that value from a file, that might help prevent us from forgetting to update in both places in the future.)

Yes, will do.
