### ISSUE TITLE
SIOP Response Payload Conflict

### ISSUE THREAD

**Issue by jdkizer9** [smart-on-fhir/health-cards#22]
There appears to be a conflict between the SIOP Response format in the reference implementation and what's in the docs. The reference implementation payload [includes](https://github.com/microsoft-healthcare-madison/health-wallet-demo/blob/bf9de724826d157689f0e0dbb3ab8926f6a32990/src/holder.ts#L245) a `did` property, whereas the payload format in the docs [includes](https://github.com/smart-on-fhir/health-cards/blob/main/docs/index.md#did-siop-response) a `sub_jwk` property. 

EDIT: I think I overlooked some things. The docs **do** include a `did` property, so just wondering if we should be including the `sub_jwk`.

**Comment by madaster97** [comment]
I think we include this because it's required for [Openid Core's SIOP Response](https://openid.net/specs/openid-connect-core-1_0.html#SelfIssuedResponse).

As for why it's in OIDC, I believe it's because that framework doesn't have a PKI setup (hence DIDs in DID SIOP). It may be worth having this explicitly removed in DID SIOP, since there is a PKI built in. I could also be missing something though!

**Comment by jmandel** [comment]
We have a `did` and `sub_jwk` property currently documented. Some of the details may change as DID-SIOP progresses through its next round of standardization. For the moment, I don't think we have anything to do on this issue, but please re-open if I'm missing something.
