### ISSUE TITLE
Determine whether adding MIME type for file downloads could provide a better "download and open" UX

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/health-cards#39]
There may be better Android handling available (e.g., routing Health Cards to the right wallet app) for downloads when a MIME type is available, vs just routing files based on extensions.

Questions:

* What behavior can we get by tapping a "download" link in browser (with extension only? With extension + MIME type?)
* What behavior can we get by tapping a "download" link on an email attachment (with extension only? With extension + MIME type?)

**Comment by madaster97** [comment]
Hey Josh,

Is this behavior specific to Android, or can iOS apps also register to a specific extension/mime-type?

I found an [article](https://www.codenameone.com/blog/associating-your-app-with-file-extension-mime-types-iphone-android-windows.html) from a few years back that covers this.

> Registering your app to open a a file type involves two parts:
> 1. Add some build hints to inject the appropriate metadata into each native platform config files (e.g. The info.plist on iOS, the manifest file on Android, etc..) to inform the native platform that the app can open the specified file types.

I'd like to try and parse out this language from DID SIOP's [UX Considerations](https://identity.foundation/did-siop/#ux-considerations).

> On Android, the user can choose which app should open if multiple apps registered the same custom URL scheme. On iOS, the behavior is undefined. One approach would be to check if the user is on an iOS device and then, won't render the button if this is a concern. A fallback on iOS could be the use of custom mime types, but unusual UX has to be considered.

Just to be clear, there are two **separate** problems there:
1. What happens when multiple apps register to a custom URL scheme (openid:)
2. What happens when multiple apps have registered to a custom mime type (extension vs mime/type?)

For the case of custom mime types on iOS, I'm unclear what _unusual UX_ means. The article above seems to indicate it's possible for one app, but maybe the unusual behavior is for several apps registering to one mime type?

**Comment by jmandel** [comment]
The reason the title here mentions Android is that the story for iOS seems to be good enough based on file type alone: it is possible to ensure that when opening a file with a particular extension (for example by clicking a link in the web browser to download it), it is routed to open in an appropriate app. For Android we have heard concerns that that type alone is not enough, and for example downloading files in a web browser will simply store them in downloads directory.

To be clear, this issue is all about what happens when you follow links to open a health card file (a `.fhir-backed-vc` file) on a device with a health wallet. The basic desired behavior is that this file can open in the wallet and the user will have the opportunity to store it there.

The points you are highlighting from DID-SIOP are about what happens when you click on a `openid://` *link* -- in practice, this has not been an issue for us because we have been focused on scenarios where these links are opened from within a wallet (e.g., the fhir `$HealthWallet.connect` operation is invoked by the wallet so no redirect into the wallet is required, and if a workflow is being kicked off by QR code, that QR code could be scanned by the wallet also). I don't mean to write this off as a non-issue, but it has not been a practical concern up to this point, and in any case it is a different issue than this (#39).

**Comment by madaster97** [comment]
I can definitely see the use case here then. To my knowledge, there seem to be a few reasons why a FHIR-backed VC may need to have a MIME type:
1. Issue above, we may NEED to specify a mime type to have the file prompt an app being opened
2. If a VC is issued for a specific wallet (of multiple on a device) then that wallet MAY want to register for a specific custom MIME type in order to correctly be the only wallet prompted (example, VC is a JWE meant for that wallet)

For scenario 1, we may as well just define a default generic MIME type, and REQUIRE that issuers publish VCs with that MIME type (or another as specified, see scenario 2). This likely needs to be required, unless this will cause unknown issues on other OSs.

For scenario 2, the app could register a custom MIME type with the issuer (see below). If the issuer was publishing a VC for that wallet specifically, then it would use that MIME type. Otherwise, issuers could default to scenario 1 for issuing VCs without a specific wallet in mind.

The custom MIME type should be decided on during the initial SIOP flow. The **SIOP response** seems to be the best place, as a new claim in the id_token. This claim could be specifically requested by the Issuer (in the SIOP Request's Scope parameter) as a new scope. Even if an issuer only supports single-wallets per user, they may want to use this claim so the user doesn't click an incorrect wallet (maybe an older one that was disconnected from their lab account, but still installed on the device). If no claim is included, OR if the issuer just didn't request one, then VCs issued for this wallet will have the generic MIME type.

**Comment by madaster97** [comment]
I think the DID SIOP spec is lacking in this space. I'd definitely be interested in drafting a PR to that spec where we delve deeper into the topic of OS specific considerations, and come up with a generic solution that should work for downloading VCs on any OS.

**Comment by jmandel** [comment]
Keep in mind that DID-SIOP is undergoing a more significant rewrite through joint work with the OpenID Foundation. https://medium.com/decentralized-identity/dif-oidf-9753b9bd0093 has background.

Regarding the case of "VC is issued for a specific wallet" -- when the FHIR issuance API is used, there shouldn't be an issue, because the wallet fetches the credential directly. If we wanted to improve the flow for other cases (which *don't* involve FHIR issuance operations), agree there's more we could do to support negotiation of wallet-specific MIME types (but I think it might be cleaner/simpler to standardize one MIME type as a start, rather than introducing a negotiation protocol).

**Comment by madaster97** [comment]
@jmandel Could you help sanity check me on the following:
1. MIME type is generally only available at download time. Even if a VC is saved to the file system, a user wouldn't be able to "invoke/open" that file later and have the MIME type be registered by the OS when opening.
2. MIME type is generally set in HTTP response headers. This restricts how files can be generated. There doesn't seem to be a way for mobile apps to generally save files with a MIME type and then invoke a download from the local file system. Files with MIME types would need to be generated from an HTTP file download from a server.

**Comment by jmandel** [comment]
1. Yes indeed. The key interaction points we care about are downloading from a web link and downloading an email attachment.

2. Yes: http headers for a web download; I should also note that for email, this can be conveyed in part-wise headers in a multipart MIME email attachment

**Comment by jmandel** [comment]
Added mime type in #64
