### ISSUE TITLE
Using ION/Sidetree

### ISSUE THREAD

**Issue by davebryson** [smart-on-fhir/health-cards#41]
While I think Sidetree is valuable as a layer 2 solution, it seems like it may be unnecessarily difficult to bootstrap the effort - especially since performance is not initially a problem.  For example:
- Someone has to run an ION/Sidetree node and manage the underlying database: [Non trivial setup](https://github.com/decentralized-identity/ion/blob/master/install-guide.md)
- The node needs to talk to Bitcoin/Ethereum to submit batched transactions, which means it has to pay transaction fees in the respective cryptocurrency.  How are these node operators compensated?  I highly doubt they’ll do this forever out of altruism
- Sidetree relies on using IPFS. So you either use the existing public IPFS network or you have to standup an IPFS node
- With all this in mind, how do you encourage the operation of multiple Sidetree nodes?  You surely don’t want just 1

**Comment by jmandel** [comment]
Thanks for these comments. Please note that the current Health Cards spec is based on the expectation that all participants will support "long-form" ion DIDs, and participants are not required to resolve ion DIDs against a a blockchain-anchored ledger (see the "Long-form vs. Short-form DIDs" note under https://healthwallet.cards/#protocol-details).

The plan is to start with `did:ion` because it (1) gives us the ability to describe sets of public keys + service endpoints in a consistent format, for issuers as well as (optionally) holders, and (2) it provides -- or at least *may well provide* -- a glide path to future capabilities like permission-less key rotation and updates, if/when we adopt full resolution.
