### ISSUE TITLE
Subject-centered claims in credentialSubject

### ISSUE THREAD

**Issue by davux** [smart-on-fhir/health-cards#47]
I understand the simplicity of embedding an FHIR bundle straight into a credential. This way the VC just acts as a container and you drop the bundle as-is.

However, while that works well for a proof of concept, stabilizing that construction would be at the cost of losing the VC data model semantics.

In VC, the `credentialSubject` JSON object represents the subject of the credential – for a health credential, that would usually be the patient. So semantically, any attribute in credentialSubject is to be read as an attribute of the patient: name, allergies, etc. See [schema.org/Person](https://schema.org/Person) for example of such attributes. As a counter-example, `fhirBundle` is not a property of a patient as it's a standalone object with resources, the patient being one of the resources.

I think it would be very good at some point to work on a subject-centered FHIR mapping. I don't have enough knowledge of the FHIR format to propose anything more concrete at this point so I'll let the specialists speak, but one step might be to split the bundle and try to represent each individual entry as a separate credential. What do you think?

Also we might need some additional claims to articulate an individual FHIR entry to a VC – maybe other health-related ontologies would be helpful there?

**Comment by jmandel** [comment]
I like this question and semantic consistency that you're driving at. It would also be good to highlight whether there are specific functional outcomes you are aiming for, because the modeling in this spec has been focused on pragmatics, given our goals and timeline.

The key design consideration that might not be obvious from the VC or linked data community perspective is that we are aiming to leverage existing semantics as well as technology implementation work from the healthcare domain. We are working with electronic health records vendors, clinical labs, and technology companies that have invested deeply (and over years) in constructing payloads that follow the FHIR standard, including FHIR JSON serialization. Since the goal is to work quickly, it's important to leverage existing data structure (even though there might be some value in attempting to decompose and integrate them more fully with other VC ecosystem schema).

A few quick notes:

* FHIR does define a set of RDF mappings that can be used for connecting the data in these bundles to other linked data; the work of applying this normalization falls on data consumers/integrators, but the mappings exist and can be applied algorithmically; https://www.hl7.org/fhir/rdf.html documents the approach

* Detailed modeling for immunization records is happening in http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/main/ which uses fhir profiling tools to establish conformance requirements; these tools and conventions may seem unusual (or even provincial!) from the VC community perspective but they are widely understood and supported among our healthcare ecosystem participants
* As for the `fhirBundle| claim, there's an interpretation that says "the credential subject is a person for whom the following bundle has been created"; so while it is perhaps an imperfect way to bridge between these worldviews, it allows us to embed and reuse semantics efficiently

**Comment by p2-apple** [comment]
Good to see this input, making us once again assert that we think we're doing the right thing!

It's clear that, on the modeling front, two worlds are colliding. As Josh mentions, our probably most important decision is to leverage existing semantics from the healthcare space, i.e. FHIR. While it would be trivial to define our own modeling to more closely align with the goal of only defining subject related properties right within `credentialSubject`, this would mean to forego creation and validation tooling that the whole healthcare industry is and has been investing in, and it would mean re-defining models that are already well defined, known and used. By sticking a complete FHIR Bundle (and its version) into `credentialSubject` we leverage a world of modeling knowledge in the healthcare space and lower the bar for implementers immensely. I believe this is a key part of our guide.

An interesting exercise for us – for a v2 – I think would be to look into splitting VCs up and how we would best link them back together.

**Comment by jmandel** [comment]
I'm closing this issue as deferred for future scope consideration. (It's still very much an area of interest, but we need to stay focused for v1.)
