### ISSUE TITLE
Are we fighting yesterday's war?

### ISSUE THREAD

**Issue by agropper** [smart-on-fhir/health-cards#94]
A JAMA perspective on vaccines and variants suggests we need to get as much experiential / real world data as we can. 

https://jamanetwork.com/journals/jama/fullarticle/2777785

IMHO, digital vaccination credentials are not enough and we need to rethink our priorities.

**Comment by jmandel** [comment]
I wish there was a way to migrate this issue over to https://github.com/smart-on-fhir/health-cards/discussions .. 

My sense is that knowing what vaccinations someone has received is an important part of a risk evaluation strategy. I don't think it'll be the only part. Understanding local infection rates, details about prevalence of particular variants, individual symptoms and history, etc will all be relevant in evaluating risk.

But I expect that knowing what specific vaccine someone received (and when) will be **part of** these strategies, and so the work we are doing on Health Cards is well placed. in particular, this is why we focus on conveying immutable facts rather than conveying risk assessments in a health card; immutable facts can be used and reused in different contexts as our understanding improves.

**Comment by agropper** [comment]
Yes, we're conveying immutable facts, but we're making a design choice to convey them by-value instead of by-reference (to a patient-controlled health record). Some of what we're doing, such as the data models and the identifiers of the actors and related trust models will persist. But the conveyance protocol - what's actually coded in the "health card" - is not resilient to the realities of the pandemic / endemic situation.
